import process from 'node:process';
import {URL} from 'node:url';
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {once} from 'node:events';
import {Pool,Client} from 'pg';
import {createApp} from '../dist/app.js';
import {createTransactionService} from '../dist/services/transactions.js';
const id='bb664829-eddd-4a27-bddc-076e8c3bf6fe';
async function server(database,run){const s=createApp({clientOrigin:'http://localhost:3000',databaseHealth:async()=>true,transactions:createTransactionService(database)}).listen(0,'127.0.0.1');await once(s,'listening');try{await run(`http://127.0.0.1:${s.address().port}/api/v1`);}finally{s.closeAllConnections();await new Promise(r=>s.close(r));}}
test('T10 deletion binds only UUID, returns empty no-store 204',async()=>{await server({query:async(sql,values)=>{assert.equal(sql,'DELETE FROM expense_tracker.transactions WHERE id = $1 RETURNING id');assert.deepEqual(values,[id]);return {rows:[{id}]};}},async base=>{const r=await globalThis.fetch(`${base}/transactions/${id}`,{method:'DELETE'});assert.equal(r.status,204);assert.equal(await r.text(),'');assert.match(r.headers.get('cache-control'),/no-store/);});});
test('T10 rejects UUID, queries and bodies before SQL',async()=>{let calls=0;await server({query:async()=>{calls++;return {rows:[]};}},async base=>{for(const [path,init] of [['invalid',{}],[`${id}?type=expense`,{}],[id,{headers:{'Content-Type':'application/json'},body:'{}'}]]){const r=await globalThis.fetch(`${base}/transactions/${path}`,{method:'DELETE',...init});assert.equal(r.status,400);assert.equal((await r.json()).error.code,'VALIDATION_ERROR');}});assert.equal(calls,0);});
test('T10 absent UUID is structured 404 and database errors are sanitized',async()=>{for(const [database,status,code] of [[{query:async()=>({rows:[]})},404,'TRANSACTION_NOT_FOUND'],[{query:async()=>{throw Object.assign(Error('SQL hostname password'),{code:'ECONNREFUSED'});}},503,'DATABASE_UNAVAILABLE'],[{query:async()=>{throw Error('SQL hostname password');}},500,'INTERNAL_ERROR']])await server(database,async base=>{const r=await globalThis.fetch(`${base}/transactions/${id}`,{method:'DELETE'});assert.equal(r.status,status);const body=await r.json();assert.equal(body.error.code,code);assert.deepEqual(body.error.details,[]);assert.doesNotMatch(JSON.stringify(body),/SQL|hostname|password/);});});
test('T10 limited-role PostgreSQL target isolation, exact summary and reconnect persistence',{skip:!process.env.T06_DISPOSABLE_DATABASE_URL},async()=>{const url=new URL(process.env.T06_DISPOSABLE_DATABASE_URL);assert.ok(['127.0.0.1','localhost'].includes(url.hostname));const admin=new Client({connectionString:url.href});await admin.connect();url.username='expense_tracker_app';url.password='';const pool=new Pool({connectionString:url.href});const service=createTransactionService(pool);const input={type:'expense',amount:'0.10',category:'food',date:'2026-09-30',description:'T10 disposable'};let a,b;try{await admin.query('DELETE FROM expense_tracker.transactions');a=await service.create(input);b=await service.create({...input,type:'income',category:'salary',amount:'0.20'});await server(pool,async base=>{assert.equal((await globalThis.fetch(`${base}/transactions/${a.id}`,{method:'DELETE'})).status,204);assert.equal((await globalThis.fetch(`${base}/transactions/${a.id}`)).status,404);assert.equal((await globalThis.fetch(`${base}/transactions/${a.id}`,{method:'DELETE'})).status,404);assert.deepEqual((await (await globalThis.fetch(`${base}/transactions`)).json()).data.map(r=>r.id),[b.id]);assert.deepEqual((await (await globalThis.fetch(`${base}/summary`)).json()).data,{totalIncome:'0.20',totalExpenses:'0.00',balance:'0.20',currency:'EGP',transactionCount:1,scope:'all'});});const reconnect=new Client({connectionString:url.href});await reconnect.connect();try{assert.equal((await reconnect.query('SELECT id FROM expense_tracker.transactions WHERE id=$1',[a.id])).rowCount,0);assert.equal((await reconnect.query('SELECT id FROM expense_tracker.transactions WHERE id=$1',[b.id])).rowCount,1);}finally{await reconnect.end();}}finally{for(const row of [a,b])if(row)await admin.query('DELETE FROM expense_tracker.transactions WHERE id=$1',[row.id]);await pool.end();await admin.end();}});
