// Real browser -> Express -> disposable PostgreSQL verification.
// Start t08-test-api.mjs with T08_DISPOSABLE_DATABASE_URL first. Never uses a remote DB.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdirSync,writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const executable=process.argv[2];if(!executable)throw new Error('Provide agent-browser executable');
const base=process.argv[3]??'http://localhost:3000';assert.equal(new URL(base).hostname,'localhost');
const control='http://127.0.0.1:4108/__test';const results=[];const artifacts=resolve('../.tmp-t10');mkdirSync(artifacts,{recursive:true});
function browser(...args) {const input=args.at(-1)?.startsWith('INPUT:')?args.pop().slice(6):undefined;const r=spawnSync(executable,['--session','expense-t08','--json',...args],{encoding:'utf8',input,timeout:30000});if(r.status!==0)throw new Error(r.stderr||r.stdout);const v=JSON.parse(r.stdout);if(!v.success)throw new Error(JSON.stringify(v));return v.data;}
const evaluate=code=>browser('eval','--stdin',`INPUT:${code}`).result;
function check(name,code) {assert.equal(evaluate(code),true,name);results.push({name,passed:true});console.log('PASS '+name);}
function verify(name,condition) {assert.ok(condition,name);results.push({name,passed:true});console.log('PASS '+name);}
function wait(code) {const deadline=Date.now()+10000;while(!evaluate(code)){if(Date.now()>deadline)throw new Error('Timed out: '+code);browser('wait','100');}}
async function configure(settings={}) {const r=await fetch(control,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});assert.equal(r.status,200);}
const evidence=async()=> {const result=await (await fetch(control)).json();result.calls=result.calls.filter(c=>c.origin==='http://localhost:3000');return result;};
function open(){browser('open',base);browser('wait','--load','networkidle');}
function ready(){wait(`!document.querySelector('section [aria-busy=true]') && document.querySelector('table tbody tr') !== null`);}
const close=()=>browser('press','Escape');

const remove=()=>browser('click',"table button[aria-label='Delete Grocery shopping']");
const confirm=()=>browser('click','dialog > div:last-child button:last-child');
async function setup(){await configure({mode:'normal',seed:true});browser('set','viewport','1440','900');open();ready();await configure({resetCalls:true});remove();}
await setup();check('Selected details and cancel focus',`document.querySelector('dialog').innerText.includes('Grocery shopping') && document.querySelector('dialog').innerText.includes('250.50') && document.querySelector('dialog').innerText.includes('Expense') && document.querySelector('dialog').innerText.includes('Food') && document.querySelector('dialog').innerText.includes('30/09/2026') && document.activeElement.textContent==='Cancel'`);close();verify('Cancel sends no DELETE',(await evidence()).calls.every(c=>c.method==='GET'));
await setup();close();browser('select','#filter-type','expense');browser('select','#filter-category','food');ready();remove();await configure({resetCalls:true});confirm();wait(`!document.querySelector('dialog') && document.body.innerText.includes('Transaction deleted.')`);wait(`!document.querySelector('section [aria-busy=true]')`);check('Success preserves filters and removes row',`document.querySelector('#filter-type').value==='expense' && document.querySelector('#filter-category').value==='food' && !document.querySelector('table tbody tr')`);check('Focus restored',`document.activeElement.id==='transactions-heading' || document.activeElement.getAttribute('aria-label')==='Delete Grocery shopping'`);let e=await evidence();verify('One bodyless DELETE and authoritative reads',e.calls.filter(c=>c.method==='DELETE').length===1&&e.calls.some(c=>c.path==='/api/v1/transactions?type=expense&category=food')&&e.calls.some(c=>c.path==='/api/v1/summary')&&e.rows.length===2);const deletedPath=e.calls.find(c=>c.method==='DELETE').path;verify('Deleted ID is 404',(await fetch('http://127.0.0.1:4108'+deletedPath)).status===404);browser('reload');wait(`!document.querySelector('section [aria-busy=true]')`);check('Deletion persists on reload',`!document.querySelector('table tbody').innerText.includes('Grocery shopping')`);
await setup();await configure({mode:'delete-pending',resetCalls:true});confirm();wait(`document.querySelector('dialog')?.innerText.includes('Deleting')`);check('Pending context and duplicate lock',`document.querySelector('dialog').innerText.includes('Grocery shopping') && [...document.querySelectorAll('dialog button')].every(b=>b.disabled)`);close();check('Pending Escape blocked',`!!document.querySelector('dialog[open]')`);wait(`!document.querySelector('dialog')`);verify('Pending sends one DELETE',(await evidence()).calls.filter(c=>c.method==='DELETE').length===1);
await setup();await configure({mode:'delete-missing',resetCalls:true});confirm();wait(`!document.querySelector('dialog') && document.body.innerText.includes('This transaction is no longer available.')`);check('Missing never reports success',`!document.body.innerText.includes('Transaction deleted.')`);verify('Missing refreshes both reads',(await evidence()).calls.filter(c=>c.method==='GET').length===2);
await setup();await configure({mode:'delete-503',resetCalls:true});confirm();wait(`document.querySelector('dialog')?.innerText.includes('Database is unavailable')`);check('Definite failure retains context and permits deliberate retry',`document.querySelector('dialog').innerText.includes('Grocery shopping') && !document.querySelector('dialog > div:last-child button:last-child').disabled && !document.querySelector('dialog').innerText.includes('SQL')`);await configure({mode:'normal'});confirm();wait(`!document.querySelector('dialog')`);verify('Deliberate retry only',(await evidence()).calls.filter(c=>c.method==='DELETE').length===2);
await setup();await configure({mode:'delete-refresh-error',resetCalls:true});confirm();wait(`!document.querySelector('dialog') && document.body.innerText.includes('Deleted, but the dashboard could not refresh.')`);check('Refresh failure retains confirmed success',`document.body.innerText.includes('Transaction deleted.')`);await configure({mode:'normal'});browser('click','main > [role=alert] button');wait(`!document.body.innerText.includes('Deleted, but the dashboard could not refresh.')`);verify('Refresh retry never repeats DELETE',(await evidence()).calls.filter(c=>c.method==='DELETE').length===1);
for(const mode of ['delete-lost','delete-500']){await setup();await configure({mode,resetCalls:true});confirm();wait(`document.querySelector('dialog')?.innerText.includes('could not confirm')`);check(mode+' gates retry',`document.querySelector('dialog > div:last-child button:last-child').disabled`);await configure({mode:'both-error'});browser('click','dialog [role=alert] button');wait(`document.querySelector('dialog')?.innerText.includes('dashboard could not refresh')`);check(mode+' failed recovery keeps gate',`document.querySelector('dialog > div:last-child button:last-child').disabled`);await configure({mode:'normal'});browser('click','dialog [role=alert] button');wait(mode==='delete-lost'?`!document.querySelector('dialog')`:`document.querySelector('dialog')?.innerText.includes('Dashboard refreshed')`);e=await evidence();verify(mode+' recovery only GET',e.calls.filter(c=>c.method==='DELETE').length===1&&e.calls.filter(c=>c.method==='GET').length===4);check(mode+' does not claim deletion success',`!document.body.innerText.includes('Transaction deleted.')`);if(mode==='delete-500'){check('Existing row permits deliberate retry',`!document.querySelector('dialog > div:last-child button:last-child').disabled`);close();}}
await configure({mode:'normal',seed:true});for(const width of [360,768,1440]){browser('set','viewport',String(width),'900');open();ready();browser('click',`${width<768?'ul':'table'} button[aria-label='Delete Grocery shopping']`);check(width+'px fits and cancel focus',`document.documentElement.scrollWidth===innerWidth && document.activeElement.textContent==='Cancel'`);verify(width+'px accessibility',browser('a11y').counts.violations===0);browser('screenshot',resolve(artifacts,'delete-'+width+'.png'),'--full');close();check(width+'px focus return',`document.activeElement.getAttribute('aria-label')==='Delete Grocery shopping'`);}
writeFileSync(resolve(artifacts,'verification.json'),JSON.stringify({results,evidence:await evidence()},null,2));console.log('Verified '+results.length+' T10 browser checks.');
