// Real browser -> unchanged T06 Express -> disposable PostgreSQL verification.
// Start t08-test-api.mjs with T08_DISPOSABLE_DATABASE_URL first. Never uses a remote DB.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdirSync,writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const executable=process.argv[2];if(!executable)throw new Error('Provide agent-browser executable');
const base=process.argv[3]??'http://localhost:3000';assert.equal(new URL(base).hostname,'localhost');
const control='http://127.0.0.1:4108/__test';const results=[];const artifacts=resolve('../.tmp-t09');mkdirSync(artifacts,{recursive:true});
function browser(...args) {const input=args.at(-1)?.startsWith('INPUT:')?args.pop().slice(6):undefined;const r=spawnSync(executable,['--session','expense-t08','--json',...args],{encoding:'utf8',input,timeout:30000});if(r.status!==0)throw new Error(r.stderr||r.stdout);const v=JSON.parse(r.stdout);if(!v.success)throw new Error(JSON.stringify(v));return v.data;}
const evaluate=code=>browser('eval','--stdin',`INPUT:${code}`).result;
function check(name,code) {assert.equal(evaluate(code),true,name);results.push({name,passed:true});console.log('PASS '+name);}
function verify(name,condition) {assert.ok(condition,name);results.push({name,passed:true});console.log('PASS '+name);}
function wait(code) {const deadline=Date.now()+10000;while(!evaluate(code)){if(Date.now()>deadline)throw new Error('Timed out: '+code);browser('wait','100');}}
async function configure(settings={}) {const r=await fetch(control,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});assert.equal(r.status,200);}
const evidence=async()=> {const result=await (await fetch(control)).json();result.calls=result.calls.filter(c=>c.origin==='http://localhost:3000');return result;};
function open(){browser('open',base);browser('wait','--load','networkidle');}
function ready(){wait(`!document.querySelector('section [aria-busy=true]') && document.querySelector('table tbody tr') !== null`);}
function submit(){browser('click','dialog button[type=submit]');}
const edit=()=>browser('click',"table button[aria-label='Edit Grocery shopping']");
const close=()=>browser('press','Escape');
await configure({mode:'normal',seed:true});browser('set','viewport','1440','900');open();ready();
await configure({resetCalls:true});edit();check('Prefills all five fields',`document.querySelector('dialog [name=type]:checked').value==='expense' && document.querySelector('dialog [name=amount]').value==='250.50' && document.querySelector('dialog [name=category]').value==='food' && document.querySelector('dialog [name=date]').value==='2026-09-30' && document.querySelector('dialog [name=description]').value==='Grocery shopping'`);browser('click','dialog [name=type][value=income]');check('Changing type clears incompatible category',`document.querySelector('dialog [name=category]').value===''`);close();verify('Cancel sends no mutation',(await evidence()).calls.every(c=>c.method==='GET'));
for(const amount of ['0.10','0.20','1000.00','999999999.99']) {
 await configure({mode:'normal',seed:true,resetCalls:true});open();ready();edit();browser('fill','dialog [name=amount]',amount);browser('fill','dialog [name=description]',`T09 exact ${amount}`);submit();wait(`!document.querySelector('dialog') && document.querySelector('table tbody')?.innerText.includes(${JSON.stringify(`T09 exact ${amount}`)})`);wait(`!document.querySelector('section [aria-busy=true]')`);
 check(`${amount} update confirmed with focus return`,`document.body.innerText.includes('Transaction updated.') && (document.activeElement.id==='transactions-heading' || document.activeElement.getAttribute('aria-label')===${JSON.stringify(`Edit T09 exact ${amount}`)})`);
 const e=await evidence(),writes=e.calls.filter(c=>c.method==='PUT');verify(`${amount} PUT exactly five string fields`,writes.length===1 && writes[0].body.amount===amount && Object.keys(writes[0].body).sort().join(',')==='amount,category,date,description,type' && Object.values(writes[0].body).every(v=>typeof v==='string'));
 verify(`${amount} refetches list and global summary`,e.calls.some(c=>c.path==='/api/v1/summary')&&e.calls.some(c=>c.path==='/api/v1/transactions'));
 const totals=await (await fetch('http://127.0.0.1:4108/api/v1/summary')).json();check(`${amount} global summary matches server`, `document.querySelector('[aria-labelledby=summary-heading]').innerText.replaceAll(',','').includes(${JSON.stringify(totals.data.totalExpenses)}) && document.querySelector('[aria-labelledby=summary-heading]').innerText.replaceAll(',','').includes(${JSON.stringify(totals.data.totalIncome)})`);
 verify(`${amount} stored exactly`,e.rows.some(r=>r.amount===amount&&r.description===`T09 exact ${amount}`));
 browser('reload');ready();check(`${amount} persists on reload`,`document.querySelector('table tbody').innerText.includes(${JSON.stringify(`T09 exact ${amount}`)})`);
}
await configure({mode:'normal',seed:true});open();ready();browser('select','#filter-type','expense');browser('select','#filter-category','food');wait(`document.querySelector('table tbody')?.innerText.includes('Grocery shopping')`);edit();browser('select','dialog [name=category]','transport');await configure({resetCalls:true});submit();wait(`!document.querySelector('dialog') && document.body.innerText.includes('It is hidden by your current filters.')`);wait(`!document.querySelector('section [aria-busy=true]')`);
check('Hidden edit preserves active filters',`document.querySelector('#filter-type').value==='expense' && document.querySelector('#filter-category').value==='food' && !document.querySelector('table tbody tr')`);const hidden=await evidence();verify('Hidden edit refetch uses current AND filters and global summary',hidden.calls.some(c=>c.path==='/api/v1/transactions?type=expense&category=food')&&hidden.calls.some(c=>c.path==='/api/v1/summary'));
for(const mode of ['put-validation','put-503','put-500','put-missing']) {
 await configure({mode:'normal',seed:true});open();ready();edit();browser('fill','dialog [name=description]','Retained edit draft');await configure({mode,resetCalls:true});submit();wait(`document.querySelector('dialog') && !document.querySelector('dialog').getAttribute('aria-busy').includes('true') && ${mode==='put-validation'?"document.querySelector('dialog [name=amount]').getAttribute('aria-invalid')==='true'":mode==='put-missing'?"document.querySelector('dialog').textContent.includes('This transaction is no longer available.')":mode==='put-500'?"document.querySelector('dialog').textContent.includes('could not confirm')":"document.querySelector('dialog').textContent.includes('Database is unavailable')"}`);
 check(`${mode} retains draft safely`,`document.querySelector('dialog [name=description]').value==='Retained edit draft' && !document.querySelector('dialog').textContent.includes('SQL secret')`);
 if(mode==='put-validation'){wait(`document.activeElement.name==='amount'`);check('Field rejection focuses amount',`document.activeElement.name==='amount'`);}
 if(mode==='put-missing'){check('Missing update disables save and offers Close',`document.querySelector('dialog button[type=submit]').disabled && [...document.querySelectorAll('dialog button')].some(b=>b.textContent==='Close')`);await configure({mode:'normal'});browser('click','dialog [role=alert] button');wait(`!document.querySelector('section [aria-busy=true]')`);check('Missing refresh keeps draft and save disabled',`document.querySelector('dialog [name=description]').value==='Retained edit draft' && document.querySelector('dialog button[type=submit]').disabled`);}
 verify(`${mode} issues one PUT`,(await evidence()).calls.filter(c=>c.method==='PUT').length===1);close();
}
await configure({mode:'normal',seed:true});open();ready();edit();browser('fill','dialog [name=description]','T09 committed uncertain');await configure({mode:'put-lost',resetCalls:true});submit();wait(`document.querySelector('dialog')?.textContent.includes('could not confirm')`);
check('Uncertain edit keeps draft and gates retry',`document.querySelector('dialog [name=description]').value==='T09 committed uncertain' && document.querySelector('dialog button[type=submit]').disabled`);await configure({mode:'both-error'});browser('click','dialog [role=alert] button');wait(`document.querySelector('dialog').textContent.includes('dashboard could not refresh')`);check('Failed read recovery retains retry gate',`document.querySelector('dialog button[type=submit]').disabled`);await configure({mode:'normal'});browser('click','dialog [role=alert] button');wait(`document.querySelector('dialog').textContent.includes('Dashboard refreshed')`);const lost=await evidence();verify('Lost response committed once, recovery only GET',lost.calls.filter(c=>c.method==='PUT').length===1&&lost.calls.filter(c=>c.method==='GET').length===4&&lost.rows.filter(r=>r.description==='T09 committed uncertain').length===1);check('Successful uncertainty check retains draft',`document.querySelector('dialog [name=description]').value==='T09 committed uncertain'`);close();
await configure({mode:'normal',seed:true});open();ready();edit();await configure({mode:'put-refresh-error',resetCalls:true});submit();wait(`!document.querySelector('dialog') && document.body.innerText.includes('Saved, but the dashboard could not refresh.')`);check('Confirmed edit distinguished from failed refresh',`document.body.innerText.includes('Transaction updated.')`);await configure({mode:'normal'});browser('click','main > [role=alert] button');wait(`!document.body.innerText.includes('Saved, but the dashboard could not refresh.')`);verify('Read recovery never repeats PUT',(await evidence()).calls.filter(c=>c.method==='PUT').length===1);
await configure({mode:'normal',seed:true});open();ready();edit();await configure({mode:'put-pending',resetCalls:true});submit();wait(`document.querySelector('dialog')?.textContent.includes('Saving')`);check('Pending edit locks controls',`[...document.querySelectorAll('dialog input,dialog select,dialog textarea,dialog button')].every(e=>e.matches(':disabled'))`);close();check('Pending Escape cannot close',`!!document.querySelector('dialog[open]')`);wait(`!document.querySelector('dialog')`);verify('Pending save sends one PUT',(await evidence()).calls.filter(c=>c.method==='PUT').length===1);
await configure({mode:'normal',seed:true});
for(const width of [360,768,1440]){browser('set','viewport',String(width),'900');open();ready();browser('click',`${width<768?'ul':'table'} button[aria-label='Edit Grocery shopping']`);check(`${width}px edit fits and focus enters`, `document.documentElement.scrollWidth===innerWidth && document.activeElement.name==='type'`);verify(`${width}px edit accessibility`,browser('a11y').counts.violations===0);browser('screenshot',resolve(artifacts,`edit-${width}.png`),'--full');close();check(`${width}px Escape returns focus`,`document.activeElement.getAttribute('aria-label')==='Edit Grocery shopping'`);}
writeFileSync(resolve(artifacts,'verification.json'),JSON.stringify({results,evidence:await evidence()},null,2));console.log(`Verified ${results.length} T09 browser checks.`);
