// Real browser -> unchanged T06 Express -> disposable PostgreSQL verification.
// Start t08-test-api.mjs with T08_DISPOSABLE_DATABASE_URL first. Never uses a remote DB.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdirSync,writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const executable=process.argv[2];if(!executable)throw new Error('Provide agent-browser executable');
const base=process.argv[3]??'http://localhost:3000';assert.equal(new URL(base).hostname,'localhost');
const control='http://127.0.0.1:4108/__test';const results=[];const artifacts=resolve('../.tmp-t11');mkdirSync(artifacts,{recursive:true});
function browser(...args) {const input=args.at(-1)?.startsWith('INPUT:')?args.pop().slice(6):undefined;const r=spawnSync(executable,['--session','expense-t08','--json',...args],{encoding:'utf8',input,timeout:30000});if(r.status!==0)throw new Error(r.stderr||r.stdout);const v=JSON.parse(r.stdout);if(!v.success)throw new Error(JSON.stringify(v));return v.data;}
const evaluate=code=>browser('eval','--stdin',`INPUT:${code}`).result;
function check(name,code) {assert.equal(evaluate(code),true,name);results.push({name,passed:true});console.log('PASS '+name);}
function verify(name,condition) {assert.ok(condition,name);results.push({name,passed:true});console.log('PASS '+name);}
function wait(code) {const deadline=Date.now()+10000;while(!evaluate(code)){if(Date.now()>deadline)throw new Error('Timed out: '+code);browser('wait','100');}}
async function configure(settings={}) {const r=await fetch(control,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});assert.equal(r.status,200);}
const evidence=async()=> {const result=await (await fetch(control)).json();result.calls=result.calls.filter(c=>c.origin==='http://localhost:3000');return result;};
function open(){browser('open',base);browser('wait','--load','networkidle');}
function fill(amount='0.10',description='T08 browser record',type='expense'){browser('click','header button');if(type==='income')browser('click','dialog [name=type][value=income]');browser('fill','dialog [name=amount]',amount);browser('select','dialog [name=category]','other');browser('fill','dialog [name=description]',description);evaluate(`(() => {const e=document.querySelector('dialog [name=date]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'2026-09-30');e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
function submit(){browser('click','dialog button[type=submit]');}

const settled=()=>wait(`!document.querySelector('[aria-labelledby=transactions-heading] [aria-busy=true]') && !document.querySelector('[aria-labelledby=summary-heading] [aria-busy=true]') && !document.querySelector('[aria-labelledby=summary-heading]').innerText.includes('Updating')`);
const select=(type,category='all')=>{browser('select','#filter-type',type);browser('select','#filter-category',category);settled();};
async function setup(settings={}){await configure({mode:'normal',seed:true,...settings});browser('set','viewport','1440','900');open();settled();evaluate(`window.__unhandled=[];addEventListener('unhandledrejection',event=>window.__unhandled.push(String(event.reason)))`);await configure({resetCalls:true});}
await setup();check('Dev server has content without framework overlay',`document.body.innerText.includes('Expense Tracker') && !document.querySelector('[data-nextjs-dialog]')`);
for(const [type,category,path,descriptions] of [['expense','all','?type=expense',['Grocery shopping','Taxi fare']],['all','food','?category=food',['Grocery shopping']],['expense','food','?type=expense&category=food',['Grocery shopping']],['all','all','',['Grocery shopping','Taxi fare','Freelance payment']]]){await configure({resetCalls:true});select(type,category);const e=await evidence();verify('Supported query '+(path||'All omitted'),e.calls.some(c=>c.path==='/api/v1/transactions'+path)&&e.calls.every(c=>c.method==='GET'&&!c.path.includes('=all')&&!c.path.includes('/summary')));check('Server rows '+(path||'All'),`${JSON.stringify(descriptions)}.every(text=>document.querySelector('table tbody').innerText.includes(text)) && document.querySelectorAll('table tbody tr').length===${descriptions.length} && document.body.innerText.includes('703.75')`);}
select('expense','food');browser('select','#filter-type','income');settled();check('Incompatible category resets',`document.querySelector('#filter-category').value==='all'`);select('income','other');browser('select','#filter-type','expense');settled();check('Other retained and unique',`document.querySelector('#filter-category').value==='other' && [...document.querySelector('#filter-category').options].filter(o=>o.value==='other').length===1`);
await setup();await configure({listDelays:{'expense:all':1600,'expense:food':1200,'income:all':50},resetCalls:true});evaluate(`window.__fetch=window.fetch;window.fetch=(url,options)=>window.__fetch(url,{...options,signal:undefined})`);browser('select','#filter-type','expense');check('Refilter has one loading announcement',`document.querySelectorAll('[aria-labelledby=transactions-heading] [role=status]').length===1`);check('Refilter hides old rows and preserves global summary',`!document.querySelector('table tbody tr') && document.body.innerText.includes('Updating transactions') && document.body.innerText.includes('703.75') && !document.querySelector('#filter-type').disabled`);browser('select','#filter-category','food');browser('select','#filter-type','income');evaluate(`document.querySelector('#filter-type').focus()`);settled();browser('wait','1800');check('Rapid changes settle on latest despite ignored abort',`document.querySelector('#filter-type').value==='income' && document.querySelector('#filter-category').value==='all' && document.querySelector('table tbody').innerText.includes('Freelance payment') && !document.querySelector('table tbody').innerText.includes('Grocery shopping') && !window.__unhandled.length`);check('Background filter refresh keeps focus',`document.activeElement.id==='filter-type'`);await configure({listDelays:{'all:all':1200},resetCalls:true});browser('find','role','button','click','--name','Reset Filters');check('Reset announces updating and keeps sensible focus',`document.body.innerText.includes('Updating transactions') && document.activeElement.id==='filter-type'`);settled();evaluate(`window.fetch=window.__fetch`);
await setup();await configure({mode:'slow-list-error',listDelays:{'expense:all':1200}});browser('select','#filter-type','expense');await configure({mode:'normal'});browser('select','#filter-type','income');settled();browser('wait','1400');check('Obsolete rejected read is silent',`!document.body.innerText.includes('Transactions could not load') && !window.__unhandled.length`);
await configure({mode:'normal',empty:true});open();settled();check('Confirmed empty database',`document.body.innerText.includes('No transactions yet') && document.body.innerText.includes('0.00')`);
await setup();select('expense','bills');check('Known nonempty filtered no-match',`document.body.innerText.includes('No transactions match these filters')`);
await configure({mode:'summary-error',seed:true});open();settled();select('expense','bills');check('Unknown global count stays neutral',`document.body.innerText.includes('No transactions to display') && document.body.innerText.includes('overall summary is unavailable') && !document.body.innerText.includes('No transactions yet') && !document.body.innerText.includes('No transactions match these filters')`);
for(const settings of [{emptyList:true,summaryCount:3},{summaryCount:0}]){await configure({mode:'normal',seed:true,...settings});open();settled();check('Conflicting snapshots marked uncertain '+JSON.stringify(settings),`document.body.innerText.includes('The list and summary may be out of date') && !document.body.innerText.includes('No transactions yet')`);if(settings.emptyList)check('Conflicting empty list stays neutral',`document.body.innerText.includes('No transactions to display')`);await configure({mode:'normal',resetCalls:true});browser('find','role','button','click','--name','Retry summary');settled();verify('Conflict recovery refreshes both reads',(await evidence()).calls.length===2);}
await setup();for(const [mode,title,path] of [['list-error','Transactions could not load','/api/v1/transactions'],['summary-error','Summary unavailable','/api/v1/summary'],['both-error','Retry all',null]]){await configure({mode});open();settled();check('Partial/full failure '+mode,`document.body.innerText.includes(${JSON.stringify(title)}) && ${mode==='list-error'?"document.body.innerText.includes('703.75')":mode==='summary-error'?"document.body.innerText.includes('Grocery shopping') && !document.querySelector('[aria-labelledby=summary-heading]').innerText.includes('0.00')":"true"}`);await configure({mode:'normal',summaryDelay:700,listDelays:{'all:all':700},resetCalls:true});if(mode==='both-error')evaluate(`(()=>{const button=[...document.querySelectorAll('main > [role=alert] button')].find(b=>b.textContent==='Retry all');button.click();button.click();})()`);else evaluate(`(()=>{const button=document.querySelector(${JSON.stringify(mode==='list-error'?"[aria-labelledby=transactions-heading] [role=alert] button":"[aria-labelledby=summary-heading] [role=alert] button")});button.click();button.click();})()`);settled();const e=await evidence();verify('Scoped deduplicated retry '+mode,path?e.calls.length===1&&e.calls[0].path===path:e.calls.length===2&&e.calls.every(c=>c.method==='GET'));}
await setup();await configure({mode:'list-validation'});browser('select','#filter-type','expense');browser('select','#filter-category','food');settled();check('Query rejection links safe selector feedback',`document.querySelector('#filter-category').getAttribute('aria-invalid')==='true' && document.querySelector('#filter-category').getAttribute('aria-describedby')==='filter-query-error' && document.body.innerText.includes('Choose a supported type and category') && !document.body.innerText.includes('SQL secret')`);await configure({mode:'normal',resetCalls:true});browser('click','[aria-labelledby=transactions-heading] [role=alert] button');settled();verify('Filter retry uses current AND query only',(await evidence()).calls.map(c=>c.path).join()==='/api/v1/transactions?type=expense&category=food');
await setup();select('expense','food');fill('0.10','T11 matching create');browser('select','dialog [name=category]','food');submit();wait(`!document.querySelector('dialog')`);settled();check('Matching create appears with filters preserved',`document.querySelector('table tbody').innerText.includes('T11 matching create') && document.querySelector('#filter-type').value==='expense' && document.querySelector('#filter-category').value==='food'`);
await setup();browser('click',"table button[aria-label='Edit Grocery shopping']");browser('select','dialog [name=category]','transport');evaluate(`(()=>{const e=document.querySelector('#filter-type');e.value='expense';e.dispatchEvent(new Event('change',{bubbles:true}));})()`);evaluate(`(()=>{const e=document.querySelector('#filter-category');e.value='transport';e.dispatchEvent(new Event('change',{bubbles:true}));})()`);submit();wait(`!document.querySelector('dialog')`);settled();check('Edit that starts matching latest filters appears without hidden warning',`document.querySelector('#filter-category').value==='transport' && document.querySelector('table tbody').innerText.includes('Grocery shopping') && !document.body.innerText.includes('hidden by your current filters')`);
await setup();select('expense','food');fill('0.10','T11 hidden reset','income');submit();wait(`!document.querySelector('dialog')`);settled();check('Hidden success is announced',`[...document.querySelectorAll('main > [role=status]')].some(e=>e.innerText.includes('hidden by your current filters'))`);evaluate(`document.querySelector('main > [role=status] button').click()`);settled();check('Reset removes contradictory hidden feedback and restores focus',`!document.body.innerText.includes('hidden by your current filters') && document.querySelector('table tbody').innerText.includes('T11 hidden reset') && document.activeElement.id==='filter-type'`);
// A summary snapshot taken before DELETE must not overwrite the confirmed new totals.
await configure({mode:'normal',seed:true,summaryDelay:4000});browser('open',base);wait(`document.querySelector('table tbody tr')!==null`);browser('click',"table button[aria-label='Delete Grocery shopping']");await configure({mode:'normal',resetCalls:true});browser('click','dialog > div:last-child button:last-child');wait(`!document.querySelector('dialog') && document.body.innerText.includes('Transaction deleted.')`);settled();browser('wait','4200');check('Post-delete refresh supersedes old summary snapshot',`document.body.innerText.includes('954.25') && !document.body.innerText.includes('703.75') && !document.querySelector('table tbody').innerText.includes('Grocery shopping')`);verify('Delete snapshot race has one mutation',(await evidence()).calls.filter(c=>c.method==='DELETE').length===1);
for(const mutation of ['POST','PUT','DELETE']){await setup();select('expense','food');if(mutation==='POST'){fill('0.10','T11 matching');browser('select','dialog [name=category]','food');}else browser('click',`table button[aria-label='${mutation==='PUT'?'Edit':'Delete'} Grocery shopping']`);await configure({mode:'normal',listDelays:{'expense:food':1800},summaryDelay:1800,resetCalls:true});if(mutation==='DELETE')browser('click','dialog > div:last-child button:last-child');else submit();wait(`!document.querySelector('dialog')`);await configure({mode:'normal'});browser('select','#filter-type','income');settled();browser('wait','1900');check(mutation+' filter change during post-write refresh stays current',`document.querySelector('#filter-type').value==='income' && document.querySelector('table tbody').innerText.includes('Freelance payment') && !document.querySelector('table tbody').innerText.includes('Grocery shopping') && !document.querySelector('table tbody').innerText.includes('T11 matching')`);const e=await evidence();verify(mutation+' performs one write and no filtered summary',e.calls.filter(c=>c.method===mutation).length===1&&e.calls.every(c=>!c.path.startsWith('/api/v1/summary?')));}
for(const [mutation,failureMode,failedPath] of [['POST','post-refresh-list-error','/api/v1/transactions'],['PUT','put-refresh-summary-error','/api/v1/summary'],['DELETE','delete-refresh-list-error','/api/v1/transactions']]){await setup();if(mutation==='POST')fill('0.10','T11 scoped save');else browser('click',`table button[aria-label='${mutation==='PUT'?'Edit':'Delete'} Grocery shopping']`);await configure({mode:failureMode,resetCalls:true});if(mutation==='DELETE')browser('click','dialog > div:last-child button:last-child');else submit();wait(`!document.querySelector('dialog') && document.body.innerText.includes('but the dashboard could not refresh')`);if(mutation==='PUT')check('Failed summary refresh labels old totals',`document.body.innerText.includes('Previously loaded totals; could not refresh.')`);await configure({mode:'normal',resetCalls:true});browser('click','main > [role=alert] button');settled();verify(mutation+' success recovery retries only failed GET',(await evidence()).calls.map(c=>c.method+' '+c.path).join()==='GET '+failedPath);await configure({mode:'list-error'});browser('select','#filter-type','income');settled();check(mutation+' later unrelated failure has no old mutation warning',`!document.body.innerText.includes('but the dashboard could not refresh')`);}
// Existing suites separately cover all uncertain mutations; exercise their retained
// drafts/context and read-only checks again under the new shared-read controller.
for(const [mutation,mode] of [['POST','post-500'],['PUT','put-500'],['DELETE','delete-500']]){await setup();if(mutation==='POST')fill('0.10','T11 uncertain');else browser('click',`table button[aria-label='${mutation==='PUT'?'Edit':'Delete'} Grocery shopping']`);await configure({mode,resetCalls:true});if(mutation==='DELETE')browser('click','dialog > div:last-child button:last-child');else submit();wait(`document.querySelector('dialog')?.innerText.includes('could not confirm')`);check(mutation+' uncertainty retains context',`${mutation==='PUT'?"document.querySelector('dialog [name=description]').value==='Grocery shopping'":`document.querySelector('dialog').innerText.includes(${JSON.stringify(mutation==='POST'?'We could not confirm':'Grocery shopping')})`} && (document.querySelector('dialog button[type=submit]')??document.querySelector('dialog > div:last-child button:last-child')).disabled`);await configure({mode:'normal',resetCalls:true});browser('click','dialog [role=alert] button');wait(`document.querySelector('dialog')?.innerText.includes('Dashboard refreshed')`);verify(mutation+' uncertainty check uses exactly two GETs',(await evidence()).calls.length===2&&(await evidence()).calls.every(c=>c.method==='GET'));browser('press','Escape');}
await setup();browser('set','media','light','reduced-motion');check('Browser actually emulates reduced motion',`matchMedia('(prefers-reduced-motion: reduce)').matches`);await configure({mode:'loading'});browser('open',base);wait(`document.querySelector('.animate-pulse')!==null`);check('Skeletons become static under reduced motion',`[...document.querySelectorAll('.animate-pulse')].every(e=>getComputedStyle(e).animationName==='none')`);settled();await configure({mode:'normal'});browser('click',"table button[aria-label='Delete Grocery shopping']");await configure({mode:'delete-pending'});browser('click','dialog > div:last-child button:last-child');wait(`document.querySelector('.animate-spin')!==null`);check('Pending spinner static under reduced motion',`getComputedStyle(document.querySelector('.animate-spin')).animationName==='none'`);wait(`!document.querySelector('dialog')`);
for(const width of [360,768,1440]){await configure({mode:'normal',seed:true});browser('set','viewport',String(width),'900');open();settled();browser('select','#filter-type','expense');browser('select','#filter-category','bills');settled();check(width+'px no-match fits',`document.documentElement.scrollWidth===innerWidth && document.body.innerText.includes('No transactions match these filters')`);verify(width+'px no-match accessibility',browser('a11y').counts.violations===0);await configure({mode:'summary-error'});browser('reload');settled();check(width+'px long unavailable/error feedback fits',`document.documentElement.scrollWidth===innerWidth`);browser('screenshot',resolve(artifacts,'recovery-'+width+'.png'),'--full');verify(width+'px error accessibility',browser('a11y').counts.violations===0);await configure({mode:'normal',seed:true});open();settled();browser('select','#filter-type','expense');browser('select','#filter-category','food');settled();fill('0.10','T11 hidden '+width,'income');submit();wait(`!document.querySelector('dialog')`);settled();check(width+'px hidden success feedback fits',`document.documentElement.scrollWidth===innerWidth && document.body.innerText.includes('hidden by your current filters')`);browser('click',`${width<768?'ul':'table'} button[aria-label='Edit Grocery shopping']`);await configure({mode:'put-refresh-summary-error'});submit();wait(`!document.querySelector('dialog') && document.body.innerText.includes('Previously loaded totals; could not refresh.')`);check(width+'px stale totals and retry fit',`document.documentElement.scrollWidth===innerWidth`);verify(width+'px stale accessibility',browser('a11y').counts.violations===0);await configure({mode:'normal',listDelays:{'income:all':1200}});browser('select','#filter-type','income');check(width+'px updating state fits with keyboard filters',`document.documentElement.scrollWidth===innerWidth && document.body.innerText.includes('Updating transactions') && !document.querySelector('#filter-type').disabled`);browser('screenshot',resolve(artifacts,'updating-'+width+'.png'),'--full');settled();}
await setup();check('Final session has no unhandled rejection',`!window.__unhandled.length && !document.querySelector('[data-nextjs-dialog]')`);writeFileSync(resolve(artifacts,'verification.json'),JSON.stringify({results,evidence:await evidence()},null,2));console.log('Verified '+results.length+' T11 browser checks.');
