import cors from "cors";
import express, { Router } from "express";
import { errorHandler } from "./middleware/error-handler.js";
import { requestPolicy, routeNotFound } from "./middleware/request.js";
import { createHealthRouter } from "./routes/health.js";
import { createTransactionRouter, createTransactionMethodRouter } from "./routes/transactions.js";
import type { TransactionService } from "./services/transactions.js";
import type { CategoryService } from "./services/categories.js";
import { createCategoryRouter } from "./routes/categories.js";
import { createRequireAuth } from "./middleware/auth.js";
import { createProfileRouter } from "./routes/profiles.js";
import type { ProfileService } from "./services/profiles.js";
import type { AccountService } from "./services/accounts.js";
import { createAccountRouter } from "./routes/accounts.js";
import type {V2TransactionService} from "./services/v2-transactions.js";
import {createV2TransactionRouter} from "./routes/v2-transactions.js";
import type {TransferService} from "./services/transfers.js";
import {createTransferRouter} from "./routes/transfers.js";

export function createApp(options: {
  clientOrigin: string;
  databaseHealth: () => Promise<boolean>;
  additionalRoutes?: Router;
  transactions?: TransactionService;
  v2Transactions?: V2TransactionService;
  transfers?: TransferService;
  categories?: CategoryService;
  profiles?: ProfileService;
  accounts?: AccountService;
  supabaseUrl?: string;
}) {
  const app = express();
  app.disable("x-powered-by");
  const api = Router();
  api.use((_request, response, next) => { response.set("Cache-Control", "no-store"); next(); });
  api.use(cors({ origin: options.clientOrigin }));
  if (options.transactions) api.use(createTransactionMethodRouter());
  api.use(requestPolicy);
  api.use(express.json({ limit: "16kb", strict: false }));
  api.use(createHealthRouter(options.databaseHealth));
  if (options.transactions) api.use(createTransactionRouter(options.transactions));
  if (options.additionalRoutes) api.use(options.additionalRoutes);
  api.use(routeNotFound);
  api.use(errorHandler);
  app.use("/api/v1", api);
  const v2 = Router();
  v2.use((_request, response, next) => { response.set("Cache-Control", "no-store"); next(); });
  v2.use(cors({ origin: options.clientOrigin }));
  v2.use(requestPolicy);
  v2.use(express.json({ limit: "16kb", strict: false }));
  v2.use(createHealthRouter(options.databaseHealth));
  if (options.categories) v2.use(createCategoryRouter(options.categories, createRequireAuth(options.supabaseUrl)));
  if (options.profiles) v2.use(createProfileRouter(options.profiles, createRequireAuth(options.supabaseUrl)));
  if (options.accounts) v2.use(createAccountRouter(options.accounts, createRequireAuth(options.supabaseUrl)));
  if (options.v2Transactions) v2.use(createV2TransactionRouter(options.v2Transactions, createRequireAuth(options.supabaseUrl)));
  if (options.transfers) v2.use(createTransferRouter(options.transfers, createRequireAuth(options.supabaseUrl)));
  v2.use(routeNotFound);
  v2.use(errorHandler);
  app.use("/api/v2", v2);
  app.use(routeNotFound);
  app.use(errorHandler);
  return app;
}
