import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const moduleUrl = source => `data:text/javascript;base64,${Buffer.from(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText).toString('base64')}`;
const {createReadRequest}=await import(moduleUrl(readFileSync(new URL('../src/lib/api/read-request.ts',import.meta.url),'utf8')));
const {countsConflict}=await import(moduleUrl(readFileSync(new URL('../src/lib/dashboard-state.ts',import.meta.url),'utf8')));
const deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
function harness(){const events=[];const reads=createReadRequest();const callbacks={start:()=>events.push('loading'),success:data=>events.push(data),error:()=>events.push('error')};return {events,reads,callbacks};}
test('T11 slower obsolete response cannot overwrite newest result even if abort ignored',async()=>{const {reads,events,callbacks}=harness();const old=deferred(),latest=deferred();let signal;const a=reads.run('expense',s=>{signal=s;return old.promise;},callbacks);const b=reads.run('income',()=>latest.promise,callbacks);assert.equal(signal.aborted,true);latest.resolve('income');assert.equal(await b,true);old.resolve('expense');assert.equal(await a,false);assert.deepEqual(events,['loading','loading','income']);});
test('T11 repeated retries share in-flight reads without duplicate loading announcements',async()=>{const {reads,events,callbacks}=harness();const pending=deferred();let calls=0;const load=()=>{calls++;return pending.promise;};const a=reads.run('all',load,callbacks);const b=reads.run('all',load,callbacks);assert.equal(a,b);assert.equal(calls,1);pending.resolve('current');assert.equal(await b,true);assert.deepEqual(events,['loading','current']);});
test('T11 confirmed mutation supersedes in-flight same-key snapshots',async()=>{const {reads,events,callbacks}=harness();const old=deferred();let signal;const a=reads.run('all',s=>{signal=s;return old.promise;},callbacks);assert.equal(await reads.run('all',async()=> 'after mutation',callbacks,true),true);assert.equal(signal.aborted,true);old.resolve('before mutation');assert.equal(await a,false);assert.deepEqual(events,['loading','loading','after mutation']);});
test('T11 cancellation and obsolete rejection are absorbed without error callbacks',async()=>{const {reads,events,callbacks}=harness();const pending=deferred();const a=reads.run('all',()=>pending.promise,callbacks);reads.cancel();pending.reject(new DOMException('aborted','AbortError'));assert.equal(await a,false);assert.deepEqual(events,['loading']);const next=deferred();const b=reads.run('food',()=>next.promise,callbacks);await reads.run('income',async()=> 'latest',callbacks);next.reject(Error('obsolete transport error'));assert.equal(await b,false);assert.deepEqual(events,['loading','loading','loading','latest']);});
test('T11 rapid filter sequence commits only latest and later retries still recover',async()=>{const {reads,events,callbacks}=harness();const responses=Array.from({length:4},deferred);const keys=['all','expense','expense:food','income'];const pending=keys.map((key,i)=>reads.run(key,()=>responses[i].promise,callbacks));responses[3].resolve('income');for(let i=2;i>=0;i--)responses[i].resolve(keys[i]);assert.deepEqual(await Promise.all(pending),[false,false,false,true]);assert.equal(events.filter(e=>e!=='loading').join(),'income');assert.equal(await reads.run('income',async()=>{throw Error('offline');},callbacks),false);assert.equal(events.at(-1),'error');assert.equal(await reads.run('income',async()=> 'recovered',callbacks),true);assert.equal(events.at(-1),'recovered');});
test('T11 list/global count conflicts are detected without inferring filtered matches',()=>{const all={type:'all',category:'all'},food={type:'expense',category:'food'};assert.equal(countsConflict(all,0,0),false);assert.equal(countsConflict(all,0,3),true);assert.equal(countsConflict(all,3,0),true);assert.equal(countsConflict(all,2,3),true);assert.equal(countsConflict(food,0,3),false);assert.equal(countsConflict(food,2,1),true);assert.equal(countsConflict(food,0,undefined),false);});
