import assert from "node:assert/strict";
import { test } from "node:test";
import { readFileSync } from "node:fs";
import ts from "typescript";
async function load(name){const s=readFileSync(new URL(`../src/lib/auth/${name}.ts`,import.meta.url),'utf8');const code=ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);}
const {safeNext,protectedPaths}=await load('redirects');
const {createSessionStore,usableSession}=await load('session-store');
const session=(id='user-a',lifetime=900)=>({access_token:'fixture',expires_at:Date.now()/1000+lifetime,user:{id,email:'fixture@example.invalid'}});
function harness(){let callback,resolve;let unsubscribed=0;const service={subscribe:cb=>{callback=cb;return {data:()=>unsubscribed++,error:null};},getSession:()=>new Promise(r=>{resolve=r;}),signOut:async()=>({data:null,error:null})};const store=createSessionStore(service);return {store,service,emit:(...args)=>callback(...args),resolve:data=>resolve({data,error:null}),get unsubscribed(){return unsubscribed;}};}
test('T08 redirects allow only exact financial paths and safe query strings',()=>{assert.equal(protectedPaths.size,8);assert.equal(safeNext('/v2/analytics?period=month'),'/v2/analytics?period=month');for(const bad of ['https://evil.invalid','//evil.invalid','/api/x','/','/v2/login','/v2/../accounts','/v2/dashboard/../../api','/v2/%2e%2e/api','/v2/dashboard\\evil','/v2/dashboard\n','/v2/dashboard/'])assert.equal(safeNext(bad),'/v2/dashboard');});
test('T08 initial state is loading/null and stale startup read cannot undo signout',async()=>{const h=harness();assert.equal(h.store.getSnapshot().loading,true);const stop=h.store.start();h.emit('SIGNED_OUT',null);h.resolve(session());await Promise.resolve();assert.equal(h.store.getSnapshot().session,null);stop();assert.equal(h.unsubscribed,1);});
test('T08 initial session, refresh and user updates preserve epoch; user changes reset it',async()=>{const h=harness();const stop=h.store.start();h.resolve(session());await Promise.resolve();const before=h.store.getSnapshot().epoch;h.emit('TOKEN_REFRESHED',session());assert.equal(h.store.getSnapshot().epoch,before);h.emit('USER_UPDATED',session());assert.equal(h.store.getSnapshot().epoch,before);h.emit('SIGNED_IN',session('user-b'));assert.ok(h.store.getSnapshot().epoch>before);stop();});
test('T08 signout clears state and failed signout preserves session',async()=>{const h=harness();const stop=h.store.start();h.resolve(session());await Promise.resolve();h.service.signOut=async()=>({error:{code:'network',message:'Try again'},data:null});assert.ok((await h.store.signOut()).error);assert.ok(h.store.getSnapshot().session);h.service.signOut=async()=>({error:null,data:null});await h.store.signOut();assert.equal(h.store.getSnapshot().session,null);stop();});
test('T08 recovery survives refresh but cannot transfer to another user',async()=>{const h=harness();const stop=h.store.start();h.emit('PASSWORD_RECOVERY',session());assert.equal(h.store.getSnapshot().recovery,true);h.emit('TOKEN_REFRESHED',session());assert.equal(h.store.getSnapshot().recovery,true);h.emit('SIGNED_IN',session('user-b'));assert.equal(h.store.getSnapshot().recovery,false);stop();});
test('T08 expiry removes session without waiting indefinitely for refresh',async()=>{const h=harness();const stop=h.store.start();h.resolve(session('user-a',0.025));await Promise.resolve();await new Promise(r=>setTimeout(r,65));assert.equal(h.store.getSnapshot().session,null);assert.equal(h.store.getSnapshot().expired,true);assert.equal(usableSession(session('user-a',-1)),false);stop();});
test('T08 unsubscribe ignores late startup resolution and subscription errors fail closed',async()=>{const h=harness();const stop=h.store.start();stop();h.resolve(session());await Promise.resolve();assert.equal(h.store.getSnapshot().session,null);const store=createSessionStore({...h.service,subscribe:()=>({data:null,error:{code:'configuration',message:'Missing config'}})});store.start()();assert.equal(store.getSnapshot().loading,false);assert.equal(store.getSnapshot().error.code,'configuration');});
